### PR TITLE
Update Prism and GetPage using new WindowManager.Current

### PR DESCRIPTION
**Pull request by albilaga**
I have some error in my app coming from MauiPopups which saying `There is no Prism Window currently displayed.` (can't replicate actually). These changes make sure to use latest stable prism so we can make it more reliable.

- Update prism to 9.0.537 (stable)
- `GetPage` now using `WindowManager.Current` so it have the same code with [Prism](https://github.com/PrismLibrary/Prism/blob/master/src/Maui/Prism.Maui/Services/PageDialogs/PageDialogService.cs#L185-L186)
- Update `Microsoft.Maui.Essentials` to 8.0.72 so it all the same to use 8.0.72 for the MAUI base

### CODE REVIEW

**Comment by thomasgalliker** [comment]
azr run

**Comment by thomasgalliker** [comment]
@albilaga can you try version [1.2.0-pre](https://www.nuget.org/packages/Popups.Maui.Prism/1.2.0-pre) of the nuget and let me know if it works?

**Comment by albilaga** [comment]
@thomasgalliker tested on test project and working perfect. Thank you :D

**Pull request merged**
